[package]
name = "darpi-headers"
version = "0.1.0-beta"
authors = ["Petar Dambovaliev <petar.atanasov.1987@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darpi = "0.1.2-beta"
derive_more = "0.99.11"